title: Intuitive Process Documentation
email: support@intuitivesystems.co.uk
description: 
baseurl: "/documentation"
url: "http://intuitive-james.github.io/documentation/"
fixedNav: 'false'
theme: grey
twitterUsername: intuitivesystem
githubUsername: intuitive-james

# collections
collections:
     transfers:
        output: true
     flights:
        output: true
     contracting:
        output: true


# Build settings
permalink: :categories/:title.html
markdown: kramdown
include: [_pages,categories]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

  defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

