title: Intuitive Development Team Process Documentation
email: support@intuitivesystems.co.uk
description: 
baseurl: "/DevelopmentTeamProcess"
url: "http://intuitivedocs.github.io/DevelopmentTeamProcess/"
fixedNav: 'false'
theme: grey

# collections
collections:
     content:
        output: true

# Build settings
permalink: :categories/:title.html
markdown: kramdown
include: [_pages,categories]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

  defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

